"""Streamlit dashboard for the Fixit voicebot RL system."""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path
from typing import Any

import pandas as pd
import streamlit as st

from src.control.inspect import inspect_policy
from src.train import load_policy


ROOT = Path(__file__).parent
OUTPUTS_DIR = ROOT / "outputs"
POLICIES_DIR = ROOT / "policies"
CONFIG_DIR = ROOT / "configs"


st.set_page_config(
    page_title="Fixit Voicebot RL Dashboard",
    page_icon="RL",
    layout="wide",
)


def _json_path(name: str) -> Path:
    return OUTPUTS_DIR / name


@st.cache_data(show_spinner=False)
def load_json(path: str) -> dict[str, Any]:
    file_path = Path(path)
    if not file_path.exists():
        return {}
    return json.loads(file_path.read_text(encoding="utf-8"))


@st.cache_data(show_spinner=False)
def load_parquet(path: str) -> pd.DataFrame:
    file_path = Path(path)
    if not file_path.exists():
        return pd.DataFrame()
    return pd.read_parquet(file_path)


def fmt_float(value: Any, digits: int = 3) -> str:
    if isinstance(value, int | float):
        return f"{value:.{digits}f}"
    return "n/a"


def run_command(command: list[str], timeout_seconds: int = 240) -> tuple[int, str]:
    try:
        completed = subprocess.run(
            command,
            cwd=ROOT,
            capture_output=True,
            text=True,
            timeout=timeout_seconds,
            check=False,
        )
    except subprocess.TimeoutExpired as exc:
        return 124, f"Command timed out after {timeout_seconds}s\n{exc}"
    return completed.returncode, (completed.stdout or "") + (completed.stderr or "")


def metric_delta(value: Any) -> str | None:
    if isinstance(value, int | float):
        return f"{value:+.3f}"
    return None


def show_missing_outputs_help() -> None:
    st.warning(
        "Some output files are missing. Run the full pipeline first: "
        "`uv run python run.py --train --eval --report`"
    )


def render_result_artifact(path: Path) -> None:
    if not path.exists():
        st.info(f"Not generated yet: `{path.relative_to(ROOT)}`")
        return

    st.caption(str(path.relative_to(ROOT)))
    if path.suffix == ".json":
        st.json(load_json(str(path)), expanded=False)
    elif path.suffix == ".parquet":
        frame = load_parquet(str(path))
        st.write(f"Rows: {len(frame):,}, Columns: {len(frame.columns):,}")
        st.dataframe(frame.head(100), use_container_width=True)
    elif path.suffix.lower() in {".png", ".jpg", ".jpeg"}:
        st.image(str(path))
    else:
        st.code(path.read_text(encoding="utf-8"), language="text")


def overview_tab() -> None:
    final_report = load_json(str(_json_path("final_report.json")))
    train_report = load_json(str(_json_path("train_report.json")))
    eval_report = load_json(str(_json_path("eval_report.json")))

    if not final_report:
        show_missing_outputs_help()

    training = final_report.get("training", {})
    offline = final_report.get("offline_evaluation", {})

    st.subheader("Run Summary")
    cols = st.columns(4)
    cols[0].metric("Active Policy", final_report.get("active_policy_version", "n/a"))
    cols[1].metric("Train Calls", training.get("data_split", {}).get("train", "n/a"))
    cols[2].metric("Val Calls", training.get("data_split", {}).get("val", "n/a"))
    cols[3].metric("Test Calls", offline.get("n_test_episodes", "n/a"))

    st.subheader("Does the learned policy improve?")
    cols = st.columns(4)
    cols[0].metric("Baseline Val Return", fmt_float(training.get("baseline_val_return")))
    cols[1].metric(
        "Learned Val Return",
        fmt_float(training.get("learned_val_return")),
        delta=metric_delta(training.get("improvement")),
    )
    cols[2].metric("Baseline Test Return", fmt_float(offline.get("baseline_test_return")))
    cols[3].metric(
        "DR Test Estimate",
        fmt_float(offline.get("dr_estimate")),
        delta=metric_delta(offline.get("improvement_vs_baseline")),
    )

    comparison = final_report.get("comparison_table", [])
    if comparison:
        st.dataframe(pd.DataFrame(comparison), use_container_width=True)

    curve_path = OUTPUTS_DIR / "learning_curve.png"
    if curve_path.exists():
        st.image(str(curve_path), caption="Learning curve generated by training")

    st.subheader("Quick Run Commands")
    st.code(
        "\n".join(
            [
                "uv sync",
                "uv run pytest -q",
                "uv run python run.py --train --eval --report",
                "uv run streamlit run streamlit_app.py",
            ]
        ),
        language="bash",
    )

    with st.expander("System capabilities"):
        capabilities = pd.DataFrame(
            [
                ("End-to-end pipeline", "uv run python run.py --train --eval --report"),
                ("Learning improvement", "outputs/train_report.json"),
                ("Learning curve", "outputs/learning_curve.png"),
                ("Offline evaluation", "outputs/eval_report.json"),
                ("Human control", "--inspect, --freeze, --rollback"),
                ("Design document", "docs/DESIGN.md"),
            ],
            columns=["Capability", "Where to find it"],
        )
        st.dataframe(capabilities, use_container_width=True, hide_index=True)

def run_files_tab() -> None:
    st.subheader("Run Pipeline Files From UI")
    st.markdown(
        """
        Use these buttons to run the same project commands from the browser. After a
        command finishes, its console output and generated result files appear below.
        """
    )

    steps: dict[str, dict[str, Any]] = {
        "1. Parse transcripts": {
            "command": ["uv", "run", "python", "run.py", "--parse-only"],
            "timeout": 120,
            "artifacts": [OUTPUTS_DIR / "parse_report.json"],
            "description": "Reads all transcript files and validates parser coverage.",
        },
        "2. Extract state features": {
            "command": ["uv", "run", "python", "run.py", "--extract-features"],
            "timeout": 180,
            "artifacts": [
                OUTPUTS_DIR / "feature_report.json",
                OUTPUTS_DIR / "feature_names.json",
                OUTPUTS_DIR / "bot_states.parquet",
            ],
            "description": "Creates interpretable bot-turn state features.",
        },
        "3. Infer bot actions": {
            "command": ["uv", "run", "python", "run.py", "--infer-actions"],
            "timeout": 180,
            "artifacts": [
                OUTPUTS_DIR / "action_report.json",
                OUTPUTS_DIR / "mdp_rows.parquet",
            ],
            "description": "Maps bot utterances to abstract dialogue actions.",
        },
        "4. Build trajectories": {
            "command": ["uv", "run", "python", "run.py", "--build-trajectories"],
            "timeout": 180,
            "artifacts": [
                OUTPUTS_DIR / "reward_report.json",
                OUTPUTS_DIR / "trajectories.parquet",
            ],
            "description": "Builds MDP transitions with rewards.",
        },
        "5. Train policy": {
            "command": ["uv", "run", "python", "run.py", "--train"],
            "timeout": 240,
            "artifacts": [
                OUTPUTS_DIR / "train_report.json",
                OUTPUTS_DIR / "learning_curve.png",
                POLICIES_DIR / "registry.json",
            ],
            "description": "Trains conservative tabular Q-learning policy.",
        },
        "6. Offline evaluation": {
            "command": ["uv", "run", "python", "run.py", "--eval"],
            "timeout": 240,
            "artifacts": [OUTPUTS_DIR / "eval_report.json"],
            "description": "Runs IPS/SNIPS and Doubly Robust OPE on test calls.",
        },
        "7. Final report": {
            "command": ["uv", "run", "python", "run.py", "--report"],
            "timeout": 60,
            "artifacts": [OUTPUTS_DIR / "final_report.json"],
            "description": "Combines training and evaluation outputs.",
        },
        "Full pipeline run": {
            "command": [
                "uv",
                "run",
                "python",
                "run.py",
                "--train",
                "--eval",
                "--report",
            ],
            "timeout": 300,
            "artifacts": [
                OUTPUTS_DIR / "train_report.json",
                OUTPUTS_DIR / "eval_report.json",
                OUTPUTS_DIR / "final_report.json",
                OUTPUTS_DIR / "learning_curve.png",
                POLICIES_DIR / "registry.json",
            ],
            "description": "Runs train, offline evaluation, and final report together.",
        },
        "Run tests": {
            "command": ["uv", "run", "pytest", "-q"],
            "timeout": 180,
            "artifacts": [],
            "description": "Runs the automated test suite.",
        },
    }

    selected = st.selectbox("Choose file/step to run", list(steps))
    step = steps[selected]

    st.info(step["description"])
    st.code(" ".join(step["command"]), language="bash")

    run_clicked = st.button(f"Run {selected}", type="primary")
    if run_clicked:
        with st.spinner(f"Running {selected}..."):
            code, output = run_command(step["command"], timeout_seconds=step["timeout"])
        st.cache_data.clear()

        if code == 0:
            st.success("Command completed successfully")
        else:
            st.error(f"Command failed with exit code {code}")

        st.subheader("Console Output")
        st.code(output or "(no output)", language="text")

        if step["artifacts"]:
            st.subheader("Generated Results")
            for artifact in step["artifacts"]:
                with st.expander(str(artifact.relative_to(ROOT)), expanded=True):
                    render_result_artifact(artifact)

    st.subheader("Existing Result Files")
    available = [
        OUTPUTS_DIR / "parse_report.json",
        OUTPUTS_DIR / "feature_report.json",
        OUTPUTS_DIR / "action_report.json",
        OUTPUTS_DIR / "reward_report.json",
        OUTPUTS_DIR / "train_report.json",
        OUTPUTS_DIR / "eval_report.json",
        OUTPUTS_DIR / "final_report.json",
        POLICIES_DIR / "registry.json",
    ]
    artifact_rows = [
        {
            "Artifact": str(path.relative_to(ROOT)),
            "Present": path.exists(),
            "Size KB": round(path.stat().st_size / 1024, 1) if path.exists() else 0,
        }
        for path in available
    ]
    st.dataframe(pd.DataFrame(artifact_rows), use_container_width=True, hide_index=True)


def architecture_tab() -> None:
    st.subheader("Solution Architecture")
    st.graphviz_chart(
        """
        digraph {
            rankdir=LR;
            node [shape=box, style=rounded];
            transcripts [label="Call transcripts"];
            parser [label="src/parser.py\\nCall + Turn objects"];
            features [label="src/features.py\\nState features"];
            actions [label="src/action_infer.py\\nAbstract actions"];
            reward [label="src/reward.py\\nProxy rewards"];
            trajectories [label="src/trajectory.py\\nMDP trajectories"];
            train [label="src/train.py + src/policy/\\nQ-learning policy"];
            eval [label="src/eval/\\nIPS + DR OPE"];
            control [label="src/control/\\nInspect, freeze, rollback"];
            outputs [label="outputs/ + policies/\\nReports and policies"];

            transcripts -> parser -> features -> actions -> reward -> trajectories;
            trajectories -> train -> eval -> outputs;
            train -> control -> outputs;
        }
        """
    )

    st.subheader("Code Map")
    code_map = pd.DataFrame(
        [
            ("Parser", "src/parser.py", "Raw transcripts to structured calls"),
            ("Features", "src/features.py", "Turn-level state features"),
            ("Actions", "src/action_infer.py", "Bot text to dialogue act"),
            ("Rewards", "src/reward.py", "Turn and terminal proxy rewards"),
            ("Trajectories", "src/trajectory.py", "Build MDP rows"),
            ("Policy", "src/policy/", "Baseline, constraints, discretizer, learner"),
            ("Evaluation", "src/eval/", "Replay, propensity, FQE, OPE"),
            ("Control", "src/control/", "Registry, inspect, freeze, rollback"),
            ("Docs", "docs/DESIGN.md", "RL design and architecture notes"),
        ],
        columns=["Area", "Path", "Purpose"],
    )
    st.dataframe(code_map, use_container_width=True, hide_index=True)

    st.subheader("MDP Summary")
    st.markdown(
        """
        - **Episode:** one phone call transcript.
        - **State:** interpretable transcript-derived features before each bot turn.
        - **Action:** abstract dialogue act such as `ASK_BUDGET`, `HANDLE_OBJECTION`, or `ACK_BUSY_DEFER`.
        - **Reward:** turn-level shaping plus terminal call outcome proxy.
        - **Policy:** conservative tabular Q-learning constrained by logged behavior support.
        """
    )


def reports_tab() -> None:
    action_report = load_json(str(_json_path("action_report.json")))
    reward_report = load_json(str(_json_path("reward_report.json")))
    eval_report = load_json(str(_json_path("eval_report.json")))
    train_report = load_json(str(_json_path("train_report.json")))

    if not any([action_report, reward_report, eval_report, train_report]):
        show_missing_outputs_help()
        return

    st.subheader("Action Distribution")
    action_distribution = action_report.get("action_distribution", {})
    if action_distribution:
        action_df = (
            pd.DataFrame(action_distribution.items(), columns=["Action", "Count"])
            .sort_values("Count", ascending=False)
            .set_index("Action")
        )
        st.bar_chart(action_df)
        st.dataframe(action_df.reset_index(), use_container_width=True, hide_index=True)

    st.subheader("Reward Components")
    reward_counts = reward_report.get("reward_component_counts", {})
    if reward_counts:
        reward_df = (
            pd.DataFrame(reward_counts.items(), columns=["Reward component", "Count"])
            .sort_values("Count", ascending=False)
            .set_index("Reward component")
        )
        st.bar_chart(reward_df)
        st.dataframe(reward_df.reset_index(), use_container_width=True, hide_index=True)

    st.subheader("Offline Evaluation")
    if eval_report:
        rows = []
        for key in ["ips", "dr"]:
            result = eval_report.get(key, {})
            if result:
                ci = result.get("ci_95", [None, None])
                rows.append(
                    {
                        "Estimator": result.get("estimator", key.upper()),
                        "Point estimate": result.get("point_estimate"),
                        "CI low": ci[0],
                        "CI high": ci[1],
                        "Episodes": result.get("n_episodes"),
                    }
                )
        if rows:
            st.dataframe(pd.DataFrame(rows), use_container_width=True, hide_index=True)

        diagnostics = eval_report.get("dr", {}).get("diagnostics", {})
        if diagnostics:
            cols = st.columns(3)
            cols[0].metric(
                "Matched Action Rate",
                fmt_float(diagnostics.get("matched_action_rate")),
            )
            cols[1].metric(
                "Low Propensity Fraction",
                fmt_float(diagnostics.get("low_propensity_fraction")),
            )
            cols[2].metric(
                "IPS Nonzero Episodes",
                diagnostics.get("ips_nonzero_weight_episodes", "n/a"),
            )

    st.subheader("Learning Curve Data")
    curve = train_report.get("learning_curve", [])
    if curve:
        curve_df = pd.DataFrame(curve).set_index("epoch")
        st.line_chart(curve_df)
        st.dataframe(curve_df.reset_index(), use_container_width=True, hide_index=True)


def policy_tab() -> None:
    registry = load_json(str(POLICIES_DIR / "registry.json"))
    policy_path = POLICIES_DIR / registry.get("active_file", "policy_active.json")

    st.subheader("Policy Registry")
    if registry:
        st.json(registry, expanded=False)
    else:
        st.warning("No registry found. Run `uv run python run.py --train` first.")

    st.subheader("Active Policy Inspection")
    if not policy_path.exists():
        st.warning(f"Active policy not found: {policy_path}")
        return

    policy = load_policy(policy_path)
    inspection = inspect_policy(policy)

    cols = st.columns(3)
    cols[0].metric("Version", inspection.version)
    cols[1].metric("State Clusters", inspection.num_states)
    cols[2].metric("Policy File", policy_path.name)

    if inspection.action_distribution:
        dist_df = (
            pd.DataFrame(
                inspection.action_distribution.items(),
                columns=["Action", "Selected states"],
            )
            .sort_values("Selected states", ascending=False)
            .set_index("Action")
        )
        st.bar_chart(dist_df)
        st.dataframe(dist_df.reset_index(), use_container_width=True, hide_index=True)

    if inspection.top_states:
        st.subheader("Top Q States")
        st.dataframe(
            pd.DataFrame(inspection.top_states[:25]),
            use_container_width=True,
            hide_index=True,
        )

    policy_data = load_json(str(policy_path))
    freeze_rules = policy_data.get("freeze_rules")
    with st.expander("Freeze rules stored in active policy"):
        st.json(freeze_rules or {}, expanded=True)


def control_tab() -> None:
    st.subheader("Human Control Commands")
    st.markdown(
        """
        These commands are the human gate for the learned policy. They do not require live users.
        """
    )

    commands = {
        "Inspect active policy": ["uv", "run", "python", "run.py", "--inspect"],
        "Diff baseline vs learned": [
            "uv",
            "run",
            "python",
            "run.py",
            "--inspect",
            "--diff",
            "baseline",
            "learned_v1",
        ],
        "Apply freeze rules": [
            "uv",
            "run",
            "python",
            "run.py",
            "--freeze",
            "configs/freeze_rules.yaml",
        ],
        "Rollback to baseline": [
            "uv",
            "run",
            "python",
            "run.py",
            "--rollback",
            "baseline",
        ],
        "Restore learned policy": [
            "uv",
            "run",
            "python",
            "run.py",
            "--rollback",
            "learned_v1",
        ],
    }

    for label, command in commands.items():
        with st.expander(label):
            st.code(" ".join(command), language="bash")
            if st.button(f"Run: {label}", key=label):
                with st.spinner(f"Running {label}..."):
                    code, output = run_command(command, timeout_seconds=90)
                if code == 0:
                    st.success("Command completed")
                else:
                    st.error(f"Command failed with exit code {code}")
                st.code(output or "(no output)", language="text")

    st.subheader("Full Pipeline")
    st.code("uv run python run.py --train --eval --report", language="bash")
    if st.button("Run full training + evaluation pipeline"):
        with st.spinner("This may take 30-90 seconds..."):
            code, output = run_command(
                ["uv", "run", "python", "run.py", "--train", "--eval", "--report"],
                timeout_seconds=300,
            )
        if code == 0:
            st.success("Full pipeline completed. Refresh the dashboard to reload cached reports.")
            st.cache_data.clear()
        else:
            st.error(f"Pipeline failed with exit code {code}")
        st.code(output or "(no output)", language="text")


def raw_artifacts_tab() -> None:
    st.subheader("Raw Output Artifacts")
    artifact_options = {
        "final_report.json": OUTPUTS_DIR / "final_report.json",
        "train_report.json": OUTPUTS_DIR / "train_report.json",
        "eval_report.json": OUTPUTS_DIR / "eval_report.json",
        "action_report.json": OUTPUTS_DIR / "action_report.json",
        "reward_report.json": OUTPUTS_DIR / "reward_report.json",
        "feature_report.json": OUTPUTS_DIR / "feature_report.json",
        "parse_report.json": OUTPUTS_DIR / "parse_report.json",
        "registry.json": POLICIES_DIR / "registry.json",
        "freeze_rules.yaml": CONFIG_DIR / "freeze_rules.yaml",
    }

    selected = st.selectbox("Choose artifact", list(artifact_options))
    path = artifact_options[selected]
    st.caption(str(path.relative_to(ROOT)))
    if not path.exists():
        st.warning("Artifact does not exist yet.")
        return

    if path.suffix == ".json":
        st.json(load_json(str(path)), expanded=False)
    else:
        st.code(path.read_text(encoding="utf-8"), language="yaml")

    st.subheader("Data Tables")
    table_options = {
        "bot_states.parquet": OUTPUTS_DIR / "bot_states.parquet",
        "mdp_rows.parquet": OUTPUTS_DIR / "mdp_rows.parquet",
        "trajectories.parquet": OUTPUTS_DIR / "trajectories.parquet",
    }
    selected_table = st.selectbox("Choose table", list(table_options))
    table_path = table_options[selected_table]
    if table_path.exists():
        frame = load_parquet(str(table_path))
        st.write(f"Rows: {len(frame):,}, Columns: {len(frame.columns):,}")
        st.dataframe(frame.head(200), use_container_width=True)
    else:
        st.info(f"{selected_table} has not been generated yet.")


def main() -> None:
    st.title("Fixit AI Voicebot RL Dashboard")
    st.caption(
        "Understand the full offline RL pipeline: data -> MDP -> learning -> OPE -> human control."
    )

    tabs = st.tabs(
        [
            "Overview",
            "Run Files",
            "Architecture",
            "Reports",
            "Policy Explorer",
            "Human Control",
            "Raw Artifacts",
        ]
    )
    with tabs[0]:
        overview_tab()
    with tabs[1]:
        run_files_tab()
    with tabs[2]:
        architecture_tab()
    with tabs[3]:
        reports_tab()
    with tabs[4]:
        policy_tab()
    with tabs[5]:
        control_tab()
    with tabs[6]:
        raw_artifacts_tab()


if __name__ == "__main__":
    sys.exit(main())
